sentry:
  dsn: "https://11661f12be644f2cad4d445c4039850a:a8e48fed4aeb4f00bf62c0261bfead9f@sentry.io/1231880"

dev:
  db:
    host: "retail.readsense.cn"
    port: "5432"
    user: "postgres"
    password: "root"
    dbname: "venus_dev"
    sslmode: "disable"
  titan:
    host: "http://114.80.100.146:8888"
    apiid: "03ec3f404d942a1eab0c541d2dc4d4e5"
    apisecret: "964afc7aaf37bb7b89232cba18afd994ca22acfa"
  kafka:
    host: "kafka-dev.senseread.com"
    port: "9092"
    group: "Group_Dev"
    topic: "frequent_customer_dev"
  grpc:
    venus: "https://retail.readsense.cn:8080"

test:
  db:
    host: "retail.readsense.cn"
    port: "5432"
    user: "postgres"
    password: "root"
    dbname: "venus_test"
    sslmode: "disable"
  titan:
    host: "http://114.80.100.146:8888"
    apiid: "03ec3f404d942a1eab0c541d2dc4d4e5"
    apisecret: "964afc7aaf37bb7b89232cba18afd994ca22acfa"
  kafka:
    host: "47.93.81.180"
    port: "9092"
    group: "Group_Test"
    topic: "frequent_customer_test"
  grpc:
    venus: "https://retail.readsense.cn:8080"

production:
  db:
    host: "117.78.27.229"
    port: "5432"
    user: "lightyear"
    password: "Cu!VhbCuQ5jk"
    dbname: "venus_production"
    sslmode: "disable"
  titan:
    host: "http://114.80.100.146:8888"
    apiid: "03ec3f404d942a1eab0c541d2dc4d4e5"
    apisecret: "964afc7aaf37bb7b89232cba18afd994ca22acfa"
  kafka:
    host: "kafka-dev.senseread.com"
    port: "9092"
    group: "Siren-Production"
    topic: "frequent_customer_production"
  grpc:
    venus: "https://lightyear.readsense.cn:8080"
